### ISSUE TITLE
Too many tests in integration suite generate a "txTooLarge" Ogmios error

### ISSUE THREAD

**Issue by rmgaray** [mlabs-haskell/singularitynet#179]
After some threshold, adding another test to the test suite ends up producing errors such as these:

```
Error: `submit` call failed. Error from Ogmios: [{"txTooLarge":{"maximumSize":16384,"actualSize":17653}}]
    at Object.exports.error (/home/rama/git/singularitynet/frontend/output/Effect.Exception/foreign.js:8:10)
    at Object.$$throw [as throw] (/home/rama/git/singularitynet/frontend/output/Effect.Exception/index.js:18:45)
    at /home/rama/git/singularitynet/frontend/output/Contract.Transaction/index.js:160:105
    at /home/rama/git/singularitynet/frontend/output/Control.Monad.Reader.Trans/index.js:108:34
    at run (/home/rama/git/singularitynet/frontend/output/Effect.Aff/foreign.js:278:22)
    at /home/rama/git/singularitynet/frontend/output/Effect.Aff/foreign.js:348:19
    at drain (/home/rama/git/singularitynet/frontend/output/Effect.Aff/foreign.js:120:9)
    at Object.enqueue (/home/rama/git/singularitynet/frontend/output/Effect.Aff/foreign.js:141:11)
    at /home/rama/git/singularitynet/frontend/output/Effect.Aff/foreign.js:339:27
    at __do (/home/rama/git/singularitynet/frontend/output/Ctl.Internal.QueryM/index.js:371:170)
```

Strangely, `skip`ping the tests does not solve the issue! Only commenting out the extra tests makes the error go away.

**Comment by rmgaray** [comment]
This can now be fixed using the latest CTL feature that allows setting a higher TX size in Plutip tests. In fact, this is already being used in this (blocked) PR: #186 .
